- README.md
- lua/modules/autocmd.lua
- lua/modules/config.lua
this adds a focus.signcolumn config wich allows us to turn on and off
cursor line toggling when entering exiting a split
> feat: added auto sign column config. fix: was not working before

- README.md
- lua/focus.lua
- lua/modules/config.lua
- lua/modules/resizer.lua
- lua/modules/split.lua
- plugin/focus.vim
This PR changes the resizing code to use the golden ration to calculate the best split.
The new big feature it adds is to split nicely. It decides if it should do a horizontal or vertical split based on the terminal size and the text width set.
```lua
vim.api.nvim_set_keymap('n', '<c-l>', ':FocusSplitNicely<CR>', { silent = true })
```
> Resize windows based on golden ratio and add support to split nicely

- lua/focus/modules/split.lua
Forgive me if I am misunderstanding how this plugin is supposed to work.  I have the following keymaps setup
```
:nnoremap <silent> <C-h> :FocusSplitLeft<CR>
:nnoremap <silent> <C-j> :FocusSplitDown<CR>
:nnoremap <silent> <C-k> :FocusSplitUp<CR>
:nnoremap <silent> <C-l> :FocusSplitRight<CR>
```
When I switch between splits, I expect things to be resized (which they are), but additionally the active buffer is replaced with a new unnamed one, which is not what I expected, since I was trying to edit an existing one.
If i'm understanding the code correctly here (a big if lol), the `enew` command is being used to ensure that the new split doesn't have the same contents as the one that was previously selected, however in my case it was wiping out the contents of an existing split as I have …
> Track split creation prior to issuing enew cmd

- README.md
- lua/focus/modules/autocmd.lua
- lua/focus/modules/config.lua
Add the `absolutenumber` option to preserver numbers on unfocussed window if `relativenumber` or `hydribenumber` is enabled.
fixes: beauwilliams/focus.nvim#58
> Add option to preserve numbers on unfocussed window

- lua/focus/modules/split.lua
This maybe related to the recent-ish breaking change in neovim.
They made most api functions that take a winnr or bufnr more strict in
requiring an integer rather than accepting nil or anything else.
> Fix FocusSplitNicely

- lua/focus/modules/config.lua
- lua/focus/modules/resizer.lua
I had the situation where I wanted to enable resizing of a buffer (whose buffer type was correctly excluded given its wider use-case but) for a particular filetype (`dan-repl`) for which I wanted it enabled. I confess this was a quick and dirty hack but thought I'd share it here to see if it might be of interest and spark some discussion around any thoughts around a better implementation 😇
> Feat: Add 'forced_filetypes' as override to 'excluded_buftypes'.

- lua/focus/modules/autocmd.lua
Recently NvimTree changed the buffer name from `NvimTree` to
`NvimTree_{number}`, this change fixes the detection in autocmd.lua
See https://github.com/kyazdani42/nvim-tree.lua/commit/0e7856fd8de18edaaee8fa0c2f2c9432c973aef5
Closes: #79
> Fix: Fixed NvimTree integration

- lua/focus/modules/autocmd.lua
I discovered a compatibility issue with [incline.nvim](https://github.com/b0o/incline.nvim) where the incline floating window wouldn't be moved after the focus.nvim autoresize. 
[incline.nvim is actually listening to `WinScrolled` to know when a pane was resized](https://github.com/b0o/incline.nvim/blob/fc2a494c42c465c61f92ca56a6d5a873866522c1/lua/incline/manager.lua#L74-L92), which also sounds like [a valid use of the event](https://neovim.io/doc/user/autocmd.html#WinScrolled). And because [the `resize()` call is delayed via `vim.schedule`](https://github.com/beauwilliams/focus.nvim/blob/86d036649ab8d00ac8fdca750533a541b892e4fb/lua/focus/modules/autocmd.lua#L27-L43), incline is getting the pane sizes _before_ the focus.nvim change. 
Firing `WinScrolled` after the auto-resize seems like …
> fire WinScrolled after delayed autoresize

- lua/focus/modules/resizer.lua
This fixes the issue with Telescope that I [mentioned](https://github.com/nvim-focus/focus.nvim/pull/106#issuecomment-1613602693), as well as an issue I was having where the LSP hover window was always too large. As far as I know floating windows shouldn't be resized, so this uses `vim.api.nvim_win_get_config` to check if the window is floating before resizing.
> fix(resize): ignore floating windows

- lua/focus/modules/autocmd.lua
- tests/test_autoresize.lua
This call fails when the current window is a terminal and is in terminal mode. Wrapping it in pcall gets rid of the issue even if it's a bit of a dirty fix.
> fix: wrap `vim.api.nvim_command` in pcall

- lua/focus/modules/functions.lua
The focus_disable function was still setting the legacy `enabled_focus_resizing` option, which is no longer used anywhere else. This just looks to be an oversight in 1aa0a6b or 493a9da.
> fix: set vim.g.focus_disable on disable

- lua/focus/modules/split.lua
Didn't need to use winlayout at all!
Resolves https://github.com/nvim-focus/focus.nvim/pull/106#discussion_r1264099547
> refactor: use vim.fn.winnr instead of wincmd

- lua/focus/modules/commands.lua
- lua/focus/modules/split.lua
- lua/focus/modules/utils.lua
Moves command definitions to Lua, and uses vim.split to split args instead of a Lua pattern.
> refactor: move command defs to lua, use vim.split

- neovim.yml
- selene.toml
Tells selene about the `vim` global so that unnecessary warnings are silenced.
> Add config for Selene linter

- lua/focus/modules/resizer.lua
- tests/test_autoresize.lua
fix: remove unnecessary uses of nvim_win_call
(moving immediate autoresize to another PR as it needs test changes)
closes #122
> fix: remove unnecessary uses of nvim_win_call

- lua/focus/modules/autocmd.lua
Fixes flickers / weird scrolling when leaving terminal buffers.
> fix: don't auto-center windows containing term buffers

- README.md
- lua/focus/modules/autocmd.lua
- lua/focus/modules/resizer.lua
- tests/test_autoresize.lua
The `splitkeep` option manages how window views are affected by switching / resizing windows. `focus.nvim` should probably follow the behavior of this option instead of using `feedkeys` to center windows with `zz`.
This PR adds an option to disable auto-centering for people using `splitkeep`. It also removes some uses of `winrestview` that were not necessary and caused some flickering with `mini.animate`.
> Remove window centering logic since it's built into nvim with `:h splitkeep`

- lua/focus/modules/resizer.lua
- tests/test_autoresize.lua
Ensures that windows are properly resized immediately when the mode is changed, instead of on the next window switch.
Also adds several tests for resizing behavior.
> fix: autoresize immediately on mode change

- lua/focus/modules/resizer.lua
- tests/test_autoresize.lua
`nvim_win_set_height` will change cmdheight if there is only one row in the layout and it is set to a height smaller than the available size. This checks cmdheight before resizing a window to avoid this issue.
fixes #131
> fix: ensure autoresize won't affect cmdheight

- lua/focus/modules/resizer.lua
Removes width / height checks, and instead stores and resets the value of `cmdheight`.
> refactor: simplify autoresize cmdheight check

- README.md
- doc/focus.txt
- lua/focus/init.lua
- lua/focus/modules/commands.lua
- lua/focus/modules/utils.lua
The `FocusToggleWindow` commands previously used buffer-local vars, which was a bit counter-intuitive due to their names. However, changing that behavior removed the ability to toggle `focus` on a per-buffer basis, which can be useful for UI buffers like `neo-tree`. This PR adds back buffer-local vars to disable focus, and adds `Focus[Enable, Disable, Toggle]Buffer` commands.
In retrospect, I think moving to window-local vars was a mistake and we should have just renamed the `Window` commands to `Buffer` imo, but this allows for the same functionality without breaking anyone's configs.
> feat: allow disabling focus for individual buffers

- lua/focus/modules/resizer.lua
There is occasionally some flicker when switching windows, when some windows sizes are fixed (neo-tree, edgy.nvim, etc.), as Focus tries to resize them even if they are disabled when a neighboring window is resized.
This PR addresses this issue by saving and restoring the window dimensions of all disabled windows when resizing, ensuring that the layout stays consistent.
This makes a *huge* difference in some cases, and pretty much eliminates flickering entirely. It also solves the issue (#114) of windows being resized by their neighbors when they shouldn't be (without using `vim.fn.winlayout()`!), allowing for more predictable resize behavior overall.
closes #114
> fix: save and restore fixed win dimensions on resize

- lua/focus/modules/resizer.lua
- tests/test_autoresize.lua
Relative may soon be delegated to *only* floats (returning nil for splits), if that's the route I/we decide to take with [this PR in core](https://github.com/neovim/neovim/pull/25550/). This PR preemptively addresses that change by checking `zindex` instead of `relative` to determine whether a window is floating. This doesn't change any behavior now, so even if that PR isn't merged there will be no side-affects from this, but this ensures we don't break any user configs if/when it is merged.
> refactor: use zindex for checking if win is float

- README.md
This setting will throw an error of `'winwidth' cannot be smaller than 'winminwidth'`, waste me hours  to find the source cause, better to write a note there
> Update README.md to add notes

- lua/focus/modules/autocmd.lua
Add `utils.is_disabled()` check when `hybridnumber` and `absolutenumber_unfocused` are both set to true.
> fix: Add missing utils.is_disabled() check

- .github/workflows/tests.yml
Update test module and test on neovim 0.10.0.
> Update test module and test on neovim 0.10.0

- README.md
- doc/focus.txt
- extras/repro.lua
- lua/focus/init.lua
- lua/focus/modules/resizer.lua
- tests/test_autoresize.lua
Adds options to set minimum width and height for the focused window. This allows users to customize the size of the focused window.
Missing tests and probably something else... If anyone has any pointers, I can continue working on this.
Motivation: I have a normal screen, but sometimes I have multiple windows with buffers open. I wanted to ensure that the focused window has at least 80 characters in width to read Markdown files comfortably.
Hope this helps the repository, which, by the way, is awesome!
> feat: add focused window minwidth and minheight options
